### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by IzzySoft** [vellt/Movies-App#10]
A scan ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for details and background) just revealed the APKs at your releases are signed using an expired debug key ("denyAfter 2019-01-01"). As that has security implications, may I ask you to please switch to a proper release key, and provide the corresponding APK signed with it? Thanks in advance!

**Comment by IzzySoft** [comment]
@vellt Any chance? Or did you abandon development of this app?

**Comment by vellt** [comment]
Yes, as you see, there is no maintenance.😕😢

**Comment by IzzySoft** [comment]
Thanks for your reply, @vellt! Of course a "no" also is an answer I accept – I just needed to be sure. So in this case, I will need to remove your app from [my repo](https://apt.izzysoft.de/fdroid). Should you one day pick up development again, be welcome to drop me a note and I can enlist it again.

So no bad feelings, we all have a "real life" – and I wish you the very best for yours, wherever your heart might lead to to!
