### ISSUE TITLE
Wish to contribute

### ISSUE THREAD

**Issue by pjnichal** [vellt/Movies-App#3]
Hey, I am Pravin Nichal. I would like to contribute in this app can you please assign me task.
This is for my open source contribution class 
please contact me at nichal.pravin2001@gmail.com

**Comment by vellt** [comment]
Hi Pravin! 😄✌️

- Step 1: Clone the repo. It's based on an older flutter version (detaild here https://github.com/vellt/Movies-App-Flutter/blob/main/pubspec.yaml).  
- Step 2: Create an imdb account, and get an API key to developing.
- Step 3: The task: You can try to start building a new screen. The new screen will load movies belonging to a category of movies. This page is loaded when you click on one of the movie categories in the movie description screen, e.g. action, and then action movie results are loaded. 
- Step 4: If you are done with this, send me a pull request and if I think it is good I will accept it and you will be also a Contributor. 🤩 

Good luck! 🍀

> The screen should look like this: 
 <img width="400" src="https://user-images.githubusercontent.com/61885011/189400628-d6787a0f-52ec-4027-beaa-48dec6be6470.png">

**Comment by pjnichal** [comment]
Thank for assign task. I'll do my best🙌

**Comment by pjnichal** [comment]
Just created pull request, please go through it,🤘

**Comment by vellt** [comment]
Great job! Welcome among the constructors! 😀👏 https://github.com/vellt/Movies-App-Flutter/graphs/contributors

**Comment by pjnichal** [comment]
🙌 Thank you for the opportunity
