### ISSUE TITLE
versioning issues

### ISSUE THREAD

**Issue by IzzySoft** [vellt/Movies-App#8]
While your latest tag suggests a version of `0.0.2`, the APK identifies the app as

    package: name='com.example.movies_app_flutter' versionCode='1' versionName='1.0.0' compileSdkVersion='31' compileSdkVersionCodename='12'

According to your release history, it should read `versionCode='2' versionName='0.0.2'` instead. The problem [originates here](https://github.com/vellt/Movies-App-Flutter/blob/main/pubspec.yaml#L18) – this line in your `pubspec.yaml` should, for the current release, be

```yaml
version: 0.0.2+2
```

and be adjusted with every release (right before tagging and building the APK). Could you please fix that? For some background:

* as the app would always show up as 1.0.0 regardless of the version installed, users would never know if they have the most recent release installed
* as `versionCode` is never changed, Android would consider them all the same version (it requires this to be increased with each release)

Thanks in advance!

**Comment by vellt** [comment]
Oh sure, thanks for the info! 😅

**Comment by IzzySoft** [comment]
Wow, that was fast – and even the APK replaced at releases, amazing! So trying to catch up: Your app will [become available here](https://apt.izzysoft.de/fdroid/index/apk/com.example.movies_app_flutter) in less than 6 hours (with the next sync around 6 pm UTC). If you wish, you can [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme. Updates will be pulled automatically within 24h of your creating a new tag and attaching an APK to it (both with the proper versioning :wink:)
